- hosts: localhost
  connection: local
  roles:
    - { role: dotfiles }
    - { role: homebrew, when: ansible_os_family == "Darwin" }
    - { role: homebrew-cask, when: ansible_os_family == "Darwin" }
    - { role: font }
    - { role: powerline }
    - { role: gitclone }

