- hosts: localhost
  connection: local
  roles:
    - { role: dotfiles }
    - { role: homebrew, when: ansible_os_family == "Darwin" }
    - { role: homebrew-cask, when: ansible_os_family == "Darwin" }
    - { role: powerline }
    - { role: zsh }
    - { role: vimperator }
    - { role: karabiner, when: ansible_os_family == "Darwin" }
    - { role: bettertouchtool, when: ansible_os_family == "Darwin" }
    - { role: gitclone }
    - { role: font }

