---

- name: Install ricty font
  homebrew: { name: 'ricty', install_options: 'powerline,patch-in-place' }
- name: Copy ttf files
  copy: src={{ item }} dest=~/Library/Fonts/
  with_fileglob:
    - /usr/local/share/fonts/Ricty*.ttf
  notify:
    - Rebuild font information cache
