---

- name: Check pip
  command: pip
  register: result
  ignore_errors: True

- name: Install pip
  command: curl -kL https://bootstrap.pypa.io/get-pip.py | python
  when: result|failed

- name: Install pip module for powerline
  pip:
    name: "{{ item }}"
    extra_args: --user
  with_items: pips

- name: Mkdir .config
  file:
    dest: ~/.config
    state: directory

- name: Create symlink for powerline
  file:
    src: ~/.dotfiles/.config/powerline
    dest: ~/.config/powerline
    state: link
    force: yes

