---

- name: Install powerline
  command: pip install --user powerline-status

- name: Create symlink for powerline
  file:
    src: ~/.dotfiles/.config/powerline
    dest: ~/.config/powerline
    state: link
    force: yes

