---

- name: Install powerline
  pip:
    name: powerline-status
    extra_args: --user

- name: Create symlink for powerline
  file:
    src: ~/.dotfiles/.config/powerline
    dest: ~/.config/powerline
    state: link
    force: yes

