---

- name: Checkout my dotfiles
  git:
    repo: https://github.com/yukimemi/dotfiles.git
    dest: ~/.dotfiles
    accept_hostkey: yes

- name: Mkdir ~/.config
  file:
    dest: ~/.config
    state: directory

- name: Create symlinks
  file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items: '{{symlinks}}'

- name: Create neovim symlinks
  file: src=~/.dotfiles/.config/nvim dest=~/.config/nvim state=link force=yes

- name: Create vimrc symlinks using neovim config.
  file: src=~/.dotfiles/.config/nvim/init.vim dest=~/.vimrc state=link force=yes

- name: Create vim symlinks using neovim config.
  file: src=~/.dotfiles/.config/nvim dest=~/.vim state=link force=yes

- name: Create fish symlinks.
  file:
    src: ~/.dotfiles/.config/fish/{{ item }}
    dest: ~/.config/fish/{{ item }}
    state: link
    force: yes
  with_items: '{{fishes}}'
