---

- name: Checkout my dotfiles
  git:
    repo: https://github.com/yukimemi/dotfiles.git
    dest: ~/.dotfiles
    accept_hostkey: yes

- name: Create symlinks
  file:
    src: ~/.dotfiles/{{ symlinks }}
    dest: ~/{{ symlinks }}
    state: link
    force: yes

