---

- name: Checkout my dotfiles
  git:
    repo: git@github.com:yukimemi/dotfiles.git
    dest: ~/.dotfiles

- name: Create symlinks
  file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items: symlinks

