---

- name: Install ricty font
  homebrew: { name: ricty, install_options: vim-powerline }
  when: ansible_os_family == "Darwin"

- name: Copy ttf files
  copy: src=/usr/local/share/fonts/ dest=~/Library/Fonts/
  when: ansible_os_family == "Darwin"
