---

- name: Install ricty font
  homebrew: { name: ricty, install_options: powerline }
  when: ansible_os_family == "Darwin"

- name: Copy ttf files
  copy: src=/usr/local/share/fonts/ dest=~/Library/Fonts/
  notify:
    - Rebuild font information cache
  when: ansible_os_family == "Darwin"
