---

symlinks:
  - .bashrc
  - .inputrc
  - .gemrc
  - .gitconfig
  - .gitignore
  - .shell-snippets
  - .tmux.conf
  - .gvimrc
  - .atom

fishes:
  - config.fish
  - fishfile
  - my_functions

vimfx:
  - vimfx
