---

symlinks:
  - .bashrc
  - .inputrc
  - .gemrc
  - .gitconfig
  - .gitignore
  - .shell-snippets
  - .tmux.conf
  - .gvimrc
  - .atom
  - .zshenv
  - .zshrc
  - .ctags

fishes:
  - config.fish
  - plugins.fish
  - functions

vimfx:
  - vimfx
