---

- name: Create symlink for Karabiner
  file:
    src: ~/.dotfiles/mac/Karabiner
    dest: ~/Library/Application Support/Karabiner
    state: link
    force: yes
  when: ansible_os_family == "Darwin"

