---

- name: Tap external Homebrew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: '{{homebrew_repositories}}'
  when: homebrew_repositories

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install/Upgrade Homebrew packages
  homebrew: name={{ item.name }} install_options={{ item.options|default() }}
  with_items: '{{homebrew_packages}}'
  when: homebrew_packages

- name: Create neovim symlinks
  file: src=~/.dotfiles/.vim dest=~/.config/nvim state=link force=yes

- name: Create neovim symlinks
  file: src=~/.dotfiles/.vimrc dest=~/.config/nvim/init.vim state=link force=yes

