---

- name: Mkdir ~/bin
  file:
    dest: ~/bin
    state: directory

- name: Clone scripts
  git:
    repo: https://bitbucket.org/yukimemi/scripts.git
    dest: ~/bin/scripts
    accept_hostkey: yes

- name: Clone private
  git:
    repo: https://github.com/yukimemi/private.git
    dest: ~/.ghq/src/github.com/yukimemi/private
    accept_hostkey: yes

- name: Create private symlinks
  file:
    src: ~/.ghq/src/github.com/yukimemi/private/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items: '{{private_symlinks}}'

- name: Create pet symlinks
  file: src=~/.ghq/src/github.com/yukimemi/private/.config/pet dest=~/.config/pet state=link force=yes

