---

homebrew_repositories:
  - sanemat/font

homebrew_packages:
  - { name: ansible }
  - { name: coreutils }
  - { name: ctags }
  - { name: exiftool }
  - { name: ffmpeg }
  - { name: fontforge }
  - { name: ghc }
  - { name: git }
  - { name: git-now }
  - { name: lua }
  - { name: lv }
  - { name: macvim, install_options: [with-lua, override-system-vim], state: head }
  - { name: mercurial }
  - { name: mobile-shell }
  - { name: mplayer }
  - { name: nkf }
  - { name: reattach-to-user-namespace }
  - { name: ssh-copy-id }
  - { name: tig }
  - { name: tmux }
  - { name: tree }
  - { name: watch }
  - { name: wget }
  - { name: youtube-dl }
  - { name: zsh, install_options: disable-etcdir }
  - { name: zsh-completions }


