---

homebrew_repositories:
  - sanemat/font
  - neovim/neovim
  - homebrew/dupes

homebrew_packages:
  - { name: ansible }
  - { name: coreutils }
  - { name: gnu-sed }
  - { name: ctags }
  - { name: go }
  - { name: exiftool }
  - { name: ffmpeg, install_options: [with-faac, with-fdk-aac, with-libass, with-x265, with-tools]}
  - { name: fontforge }
  - { name: git }
  - { name: imagemagick }
  - { name: lua }
  - { name: lv }
  - { name: python3 }
  - { name: macvim, install_options: [with-lua, with-override-system-vim, with-python3], state: head }
  - { name: neovim }
  - { name: mobile-shell }
  - { name: reattach-to-user-namespace }
  - { name: ssh-copy-id }
  - { name: tig }
  - { name: tmux, install_options: [with-utf8proc], state: head }
  - { name: youtube-dl }
  - { name: source-highlight }
  - { name: packer }
  - { name: grep }
  - { name: mas }
  - { name: fish }
  - { name: zsh, install_options: [with-unicode9, without-etcdir] }

